### PR TITLE
Not complete but some examples of what you can consider changing

### PR DESCRIPTION
**Pull request by smitch88**
Good luck with your endeavors :) I think you are making great progress. I couldn't actually get the setup to load properly since there is no "seeding" for the songs collection.

However, I did go thru some of the code on both sides and adjust things you may want to consider. Let me know if you have any questions.

My background just for context,

Senior software engineer w/ focus on frontend and backend node

Obviously don't merge this, just easier than writing suggestions in reddit :)

Couple of ideas to look into

1. Adding package.json scripts at the top level to do both installs at the same time
2. Adding `prettier` and `eslint` for auto formatting and code consistency

### CODE REVIEW

**Comment by nobodyme** [comment]
Thanks a lot man, that was really helpful. Will definitely make those changes, that was detailed and very helpful and about eslint and prettier. Yes, I tried to add them earlier but having them know about each other's responsibilities along with their integration into VS code was a little too much to handle when I first learnt about them. Will give it another try. Have a nice day :)

PS: And about the seeding, I actually added them separately as a csv file in the repo along with instructions to setup them up in the readme, but having read you comment, I guess should have integrated that as a npm script into the code.

**Comment by nobodyme** [comment]
Hey, just one question, when does that `componentDidUpdate` in fetchSongDetail come into play? I read that the lifecycle method is called when the component updates ie it receives props or changes state. So componentDidMount already fetches the data that it requires when it mounts and there are no state updates after that since it has no interactive components. So when does it come into play or I don't understand the lifecycle method properly?

**Comment by smitch88** [comment]
In your specific case it's possible its not necessary since you are using
the router and that may always remount the component on the URL change.
That may not always be the case in your code, e.g a sub component also runs
a fetch but it's based on a prop like an id instead.

It all comes down to whether the component is "remounting" or not.
componentDidMount only gets fired once so if you have situations where
props change and you need to refire something you did in componentDidMount
like an async fetch you would need to check for the props change diff and
run the logic again in componentDidUpdate.

**Comment by nobodyme** [comment]
Yes, great, got it, thanks for the quick reply :)

**Pull request closed without merging**
